### PR TITLE
Add licensing module ordering

### PR DESCRIPTION
**Pull request by LourensVeen**
This orders the Licensing module using the new metadata tags, and introduces shorter titles for the title cards. I haven't managed to test it locally, but am hoping for the best :smile:.

See #51.

### CODE REVIEW

**Comment by JaroCamphuijsen** [comment]
@LourensVeen should someone review this PR? Can you request someone?

**Comment by LourensVeen** [comment]
Oh yeah probably, now that we're done teaching and it won't change in the middle of the lesson :smile:.

**Review by Cmurilochem — CHANGES_REQUESTED** [review]
Hi @LourensVeen. I made a local rendering of your module and it looks great. 

I see that it is very complete and has several nice chapters. Your shorter titles helped to clean up a bit its appearance. 

Because you are already with "the hands on duty" , it would be nice if you could complete the `Learning objectives` chapter. This can be done by adding bullet points to the `info.md` file; see, *e.g.*, [here](https://github.com/esciencecenter-digital-skills/research-software-support/blob/main/modules/testing/info.md)

Thanks!

**Comment by LourensVeen** [comment]
Yes, I should do that, but probably in a new PR in the next sprint in two weeks. This one already makes two changes and I'd rather not let the scope creep any further.

**Review by Cmurilochem — APPROVED** [review]
Agreed. I will create an issue for that and assign it to you. I will approve this PR...

**Comment by LourensVeen** [comment]
I'm just going to be so bold as to merge this. It's Friday after all. YOLO!

**Pull request merged**
