### PR TITLE
Software Publication new format migration

### LINKED ISSUE #42: Adapt `Software publication` module to new format

### PR DESCRIPTION
**Pull request by Cmurilochem**
This PR closes #42.

# Tasks
- [x] Move slides `md` file outside `media/` and update figure paths.
- [x] Change slides extension from `md` to `pmd`
- [x] Add `discussion.md` file. 
- [x] Add `software_publication_pipeline.md` file.
- [x] Add `automating_software_publication.md` file
- [x] Add exercise `md` file.
- [x] Add `Reading material` as an additional `reading.md` file.
- [x] Clean up main `publication.md` file.
- [x] Add numerical values to filenames to sort chapter order

### CODE REVIEW

**Comment by Cmurilochem** [comment]
@JaroCamphuijsen and @c-martinez. Could not really find dedicated guides for software publication. Available info often comes intertwined with software citation. Please, let me know of you know any besides those infos contained in Turing way and Carpentries.

**Review by JaroCamphuijsen — CHANGES_REQUESTED** [review]
HI Carlos, this looks great. We settled on a new convention to sort the chapters by using numerical values at the start of each filename, so `discussion.md` should be `01.discussion.md`, etc. Could you add this?

**Comment by Cmurilochem** [comment]
> HI Carlos, this looks great. We settled on a new convention to sort the chapters by using numerical values at the start of each filename, so `discussion.md` should be `01.discussion.md`, etc. Could you add this?

Thanks @JaroCamphuijsen. Done!

**Comment by Cmurilochem** [comment]
> Hi @Cmurilochem , if I understand your question correctly, you are looking for guides that explain "Why is it important to publish software", more than "how do you make sure your software is citable (add a CFF file"?
> 
> Are the [Software citation principles](https://force11.org/info/software-citation-principles-published-2016/) and [CRedIT](https://credit.niso.org/) taxonomy more what you are looking for?

Thanks @c-martinez. The `Software citation principles` is one example that I was looking for and already helps so much! Thanks!!

**Review by JaroCamphuijsen — APPROVED** [review]

**Pull request merged**
