### PR TITLE
Update the list of software that can be used for the exercise in the SMP

### LINKED ISSUE #98: Use different software examples
In the [Software Management Plan module](https://esciencecenter-digital-skills.github.io/research-software-support/modules/softwaremanagementplans/softwareassessment) we have the following example software in the exercise:

[Xenon](https://research-software-directory.org/software/xenon)
[ESMValTool](https://research-software-directory.org/software/esmvaltool)
[RS-DAT](https://research-software-directory.org/projects/rs-dat)
[Haddock](https://research-software-directory.org/software/haddock3)
[worcs](https://cjvanlissa.github.io/worcs/index.html)

They are not representative for the software/code that the audience is dealing with. Also, some of the above are not software, but whole projects with various related pieces of software. We need new and better examples.

**New examples should be a mix of:**
- Software management levels (scripts, packages, infrastructures)
- Domains (life science, env sus, etc.)
- Applied vs fundamental science

### PR DESCRIPTION
**Pull request by luisaforozco**
I propose the following list of software to cover many domains, languages and size of the code. Here are brief descriptions:
- [ESMValTool](https://research-software-directory.org/software/esmvaltool): big tool, domain: climate. 
- [Cross-Perspective Topic Modeling](https://research-software-directory.org/software/cptm): collection of scripts python, domain: humanities.
- [LitStudy](https://github.com/NLeSC/litstudy/): small python tool, self-contained, cross-domain.
- [Haddock](https://research-software-directory.org/software/haddock3): medium size chemistry research tool written in python and Fortran.
- [worcs](https://cjvanlissa.github.io/worcs/index.html): R, tool for assessing openness 
- [Xenon](https://research-software-directory.org/software/xenon): big tool, java

## Extra TODOs
- [x] This list could also be updated in the exercise [research life cycle](https://esciencecenter-digital-skills.github.io/research-software-support/modules/researchsoftware/exercise-research-life-cycle).

Closes #98

### CODE REVIEW

**Review by raar1 — APPROVED** [review]
Looks good! I think it's much better now that all links go to actual software. I agree with the tools you added, although I think it's a bit weird that the "Get Started" button goes to the github repo for one and to the docs for the other (but this isn't your fault). I suppose people will mainly navigate to the code repo for this task?

I completely agree with updating the list for the research lifecycle. Can you make an issue for it if there isn't already one there?

**Comment by luisaforozco** [comment]
Thanks @raar1.
i've updated the issue and added the changes in commit [58e2c0d](https://github.com/esciencecenter-digital-skills/research-software-support/pull/99/commits/58e2c0dc45114d19b2057ee54cb083efe9e7232f).
@JaroCamphuijsen what do you think, is this ready to merge?

**Comment by JaroCamphuijsen** [comment]
I would remove Xenon from this list as I would actually not even regard that as research software, but just software used in research. It's a nice and handy development tool if you are using remote machines. I think having ESMValTool as the "big tool" is enough, it would also really need the highest level of software management as it is being used for the IPCC reports (I'm not sure whether that management level is actually met, but that's another issue 😄  ). 

In the documentation module PR #31 Max also suggested a different piece of software: [Democracy Topic Modelling](https://research-software-directory.org/software/democracy-topic-modelling)

Do you think it would be good to align and have one set of examples throughout all the content? This will probably make it easier for maintenance and preparing for teaching.

**Comment by JaroCamphuijsen** [comment]
> Looks good! I think it's much better now that all links go to actual software. I agree with the tools you added, although I think it's a bit weird that the "Get Started" button goes to the github repo for one and to the docs for the other (but this isn't your fault). I suppose people will mainly navigate to the code repo for this task?
> 
> I completely agree with updating the list for the research lifecycle. Can you make an issue for it if there isn't already one there?

@raar1 well, yeah that is actually a good point, will people generally navigate to the github repo? I'm not sure... I would, but they are not me. Maybe we should provide instructions...

**Comment by raar1** [comment]
I think this looks good now, but PR had been lying around for a while so maybe you could take a quick look at it (render locally) @JaroCamphuijsen ?

**Review by JaroCamphuijsen — APPROVED** [review]
I think this looks like a good varied list. I added the list in a couple of places where it was not changed yet. I also moved the discussion from the publication chapter to the slideshow, because I think it makes more sense there and is a tiny change for which we don't need an extra PR.

**Pull request merged**
